### ISSUE TITLE
Az.Boostrap / Install-AzProfile - PowerShellGet - Parameter typo

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azurestack-powershell#119]
Typo in module incorrectly refers to PowerShellGet's "AllowPreReleaseVersions" when it instead should be "AllowPreRelease"

When running
```
Install-AzProfile -Profile 2020-09-01-hybrid -Force
```
per instructions on [Post deployment configurations for ASDK](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-post-deploy?view=azs-2102&tabs=az1%2Caz2%2Caz3#install-azure-stack-powershell) - error message is received:

```
Install-Package : A parameter cannot be found that matches parameter name 'AllowPrereleaseVersions'.
At C:\Program Files\WindowsPowerShell\Modules\powershellget\2.2.5\PSModule.psm1:9711 char:68
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

PowerShellGet may need to be updated beyond the default OS installed version 1.0.0.1 (latest is currently 2.2.5) in order to support the 'AllowPreRelease' parameter, if true, this should be taken into account for the Install-AzProfile cmdlet.

**Comment by bganapa** [comment]
@CHDAFNI-MSFT  Were you able to workaround the issue here?  You are making a point only about the the parameter naming
AllowPreReleaseVersions usage instead of  AllowPreRelease?

**Comment by bganapa** [comment]
i just made sure that the module az.bootstrapper is using the AllowPrerelease wherever needed
https://github.com/Azure/azurestack-powershell/blob/dev/src/Az.BootStrapper/Module/Az.Bootstrapper.psm1

The typo is likely coming from PowershellGet module itself.
