### ISSUE TITLE
AzureStack module fails to load in linux environments

### ISSUE THREAD

**Issue by bganapa** [Azure/azurestack-powershell#14]
To Repro Simply install AzureStack module in Linux with the instructions from https://aka.ms/az4azurestack and Load the uber module AzureStack

PS /> Import-Module AzureStack -Verbose
VERBOSE: Loading module from path '/root/.local/share/powershell/Modules/AzureStack/2.0.0/AzureStack.psd1'.
Import-Module: The required module 'Azs.AzureBridge.Admin' is not loaded. Load the module or remove the module from 'RequiredModules' in the file '/root/.local/share/powershell/Modules/AzureStack/2.0.0/AzureStack.psd1'.

Root Cause
The published modules Azs.AzureBridge.Admin , Azs.InfrastructureInsights.Admin and Azs.KeyVault are not recognized as modules due to case sensitivity. e.g. the Published module is Azs.Azurebridge.Admin, but ht psd1 file name is Azs.AzureBridge.Admin and the Uber module AzureStack refers to the Module as Azs.AzureBridge.Admin

**Comment by bganapa** [comment]
PR is here https://github.com/Azure/azurestack-powershell/pull/15

**Comment by bganapa** [comment]
@cblackuk FYI

**Comment by bganapa** [comment]
AzureStack 2.0.1-preview release is out

**Comment by cblackuk** [comment]
Thank you! Tested and 2.0.1 loads now :-)
