### ISSUE TITLE
AzureStack 2.3.0 missing from PowerShell Gallery

### ISSUE THREAD

**Issue by wturner123** [Azure/azurestack-powershell#165]
As per title, the latest module release is not available in PowerShell Gallery to install/download.

**Comment by cblackuk** [comment]
Yep: 
![image](https://github.com/Azure/azurestack-powershell/assets/28607803/e6ce9c95-cf09-4be9-8dea-7e046ac61cee)

**Comment by wturner123** [comment]
[2.3.0](https://www.powershellgallery.com/packages/AzureStack/2.3.0) is now available :)

**Comment by cblackuk** [comment]
Seems to be now resolved :) 
![image](https://github.com/Azure/azurestack-powershell/assets/28607803/899bc759-fad3-4cc8-bca5-3e670a665906)
