### ISSUE TITLE
In 2.0.1 in azs.fabric.admin Disable-AzsScaleUnitNode kicks off ScaleUnitNodesStopMaintenanceMode, while EnableAzsScaleUnitNode kicks off ScaleUnitNodesStartMaintenancemode

### ISSUE THREAD

**Issue by nimeader** [Azure/azurestack-powershell#23]
In 2.0.1 in azs.fabric.admin Disable-AzsScaleUnitNode kicks off ScaleUnitNodesStopMaintenanceMode, while EnableAzsScaleUnitNode kicks off ScaleUnitNodesStartMaintenancemode, so the cmdlets appear to be switched

**Comment by cblackuk** [comment]
Thank you!

**Comment by bganapa** [comment]
@LingyunSu The issue is in the renaming of the cmdlets in the readme.md here https://github.com/Azure/azurestack-powershell/blob/master/src/Azs.Fabric.Admin/readme.md Disable should do Start-*MaintenanceMode*, not Stop-*MaintananeMode*

**Comment by LingyunSu** [comment]
Issue fixed. PR:
https://github.com/Azure/azurestack-powershell/issues/23

**Comment by LingyunSu** [comment]
New PR: https://github.com/Azure/azurestack-powershell/pull/28

**Comment by bganapa** [comment]
The release is out
https://github.com/Azure/azurestack-powershell/releases/tag/v2.0.2-preview
