### ISSUE TITLE
Invalid identity for URI for Remove-AzsAzureBridgeDownloadedProduct

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azurestack-powershell#29]
I remember filing a similar issue for this a long time ago, but the issue is still there with his command. Invalid identity for URI for Remove-AzsAzureBridgeDownloadedProduct is caused by the ProductResource object being piped to Remove-AzsAzureBridgeDownloadedProduct:

`$azMktplaceVersion | Remove-AzsAzureBridgeDownloadedProduct`

Here is the error:

```
Remove-AzsAzureBridgeDownloadedProduct_DeleteViaIdentity: Invalid identity for URI '/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.AzureBridge.Admin/activations/{activationName}/downloadedProducts/{productName}'
```

I believe this is caused by the fact that productName has "Default/" in the name, when the official name should be what follows "Default/".

**Comment by bganapa** [comment]
@ionuttulai Can you pls plan to fix this issue? if not let us know

**Comment by bganapa** [comment]
This is happenign only with piping. Workaround is to use the -ResourceId or the -Name parameter
