### ISSUE TITLE
Azure Bridge Bad Request Errors

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azurestack-powershell#32]
We have been getting bad request errors for Invoke-AzsAzureBridgeProductDownload and Remove-AzsAzureBridgeDownloadedProduct. The error looks like the following:

```
FINALLY Response: 'StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  Date: Thu, 16 Jul 2020 04:25:53 GMT
  Connection: close
  Content-Type: text/html; charset=us-ascii
  Content-Length: 346
}'
FINALLY Value: '0'
VERBOSE: INFORMATION: FINALLY ExtendedData Type: ''
FINALLY ExtendedData ''
DEBUG: Finally:
Remove-AzsAzureBridgeDownloadedProduct_Delete: The server responded with a Request Error, Status: BadRequest
```

The issue is caused by appending of request headers from previous requests to the new request until the size of the request header is too large and it becomes a bad request.

**Comment by bganapa** [comment]
@ionuttulai Could you please work @TheOnlyWei to look at this issue?

**Comment by bganapa** [comment]
This is due to autorest issue, it is adding extra header for every poll , resulting in a looong header

**Comment by bganapa** [comment]
@TheOnlyWei did we file an autorest issue here? could you pls link?

**Comment by TheOnlyWei** [comment]
I emailed the appropriate team for this issue, and they seem to have fixed it.
