### ISSUE TITLE
AzureStack 1.7.2 module is not catalog signed

### ISSUE THREAD

**Issue by SamaraSoucy-MSFT** [Azure/azurestack-powershell#51]
Original Post: [https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1580](https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1580)

Text:
While customer was installing version 1.7.2, the below error was appearing

The version '0.2.3' of the module 'Azs.Storage.Admin' being installed is not catalog signed. Ensure that the version '0.2.3' of the module 'Azs.Storage.Admin' has the catalog file 'Azs.Storage.Admin.cat' and signed with the same publisher 'CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'Azs.Storage.Admin' with version '0.3.1' under the directory 'C:\Program Files\WindowsPowerShell\Modules\Azs.Storage.Admin\0.3.1'. If you still want to install or
update, use -SkipPublisherCheck parameter., update aborted.

Version 1.8.2 was installed, and there is automated script that was installing version 1.7.2, which is not acceptable to be modified by customer to add switch -SkipPublisherCheck, could you help advising why the catalog file is missing , or what is wrong here?

**Comment by bganapa** [comment]
The issue happens only when trying to install 1.7.2 side by side with 1.8.2


Install-Module -Name AzureStack -RequiredVersion 1.8.2 # Preinstalled version
Install-Module -Name AzureStack -RequiredVersion 1.7.2
# Throws error

Install-Module -Name AzureStack -RequiredVersion 1.8.2 # Preinstalled version
Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force -Verbose -ErrorAction Continue
Install-Module -Name AzureStack -RequiredVersion 1.7.2
# Also throws error


With some testing I was able to get it to work this way: 

Install-Module -Name AzureStack -RequiredVersion 1.8.2 # Preinstalled version
Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force -Verbose -ErrorAction Continue
Remove-Item "C:\Program Files\WindowsPowerShell\Modules\AzureStack" -Recurse -Force
Install-Module -Name AzureStack -RequiredVersion 1.7.2

**Comment by bganapa** [comment]
This is not a supported scenario. This happens with Az powershell as well while doing a side by side force install

**Comment by bganapa** [comment]
Closing this as wont fix. side by side install is not supported
